### ISSUE TITLE
SyntaxError: Unexpected token > in JSON at position 1

### ISSUE THREAD

**Issue by escobar5** [newrelic/newrelic-introspector-node#16]
## Description

When New Relic is installing Node Agent, this error appears and then it says 'No Node processes found running on the host':

```
SyntaxError: Unexpected token > in JSON at position 1
    at JSON.parse (<anonymous>)
    at pm2List (/usr/local/lib/node_modules/@newrelic/introspector-node/src/utils.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.list [as handler] (/usr/local/lib/node_modules/@newrelic/introspector-node/src/commands.js:12:23)
```

## Steps to Reproduce

1. I had to install manually introspector-node with: `npm i -g @newrelic/introspector-node`
2. Then run newrelic script: `curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=<api_key> NEW_RELIC_ACCOUNT_ID=<accid> /usr/local/bin/newrelic install`

## Expected Behavior

Should not throw an Error

## Relevant Logs / Console output

```
SyntaxError: Unexpected token > in JSON at position 1
    at JSON.parse (<anonymous>)
    at pm2List (/usr/local/lib/node_modules/@newrelic/introspector-node/src/utils.js:12:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.list [as handler] (/usr/local/lib/node_modules/@newrelic/introspector-node/src/commands.js:12:23)
```

## Your Environment

Ubuntu 22.04.1

**Comment by escobar5** [comment]
The error seems to happen when pm2 is outdated, it may be because pm2 list changes and a message is prepended to the output, so it may be confusing the parser:

> \>>>> In-memory PM2 is out-of-date, do:
> \>>>> $ pm2 update


The solution is to pm2 update first, and then run the newrelic-introspector-node or the new relic script

**Comment by kidk** [comment]
Thanks for adding the solution @escobar5 ❤️
